### ISSUE TITLE
sir for the following test case  is not working  for your code can you please explain it  sir

### ISSUE THREAD

**Issue by aswinkumarpopuri** [scottnakada/HackerRank-Java#1]
Input (stdin)
1 1 1 0 0 0
0 1 0 0 0 0
1 1 1 0 0 0
0 9 2 -4 -4 0
0 0 0 -2 0 0
0 0 -1 -2 -4 0

**Comment by scottnakada** [comment]
Aswinkumarpopuri,
   Thank you for taking the time to try my code.  I did this a while ago.  Can you tell me which problem you were testing?
                       Scott

**Comment by aswinkumarpopuri** [comment]
https://www.hackerrank.com/challenges/2d-array

The above link Data strucutres Array 2D problem

**Comment by scottnakada** [comment]
Aswinkumarpopuri,
     This is the output that my program generates for the input data set you
provided.  It looks like the answer should be 13, for the hourglass at (1,0).

Checking hourglass at (1,0)
0 1 0
  1
0 9 2
hour glass sum = 13

What answer were you expecting?

# Full output from the program

1 1 1 0 0 0 
0 1 0 0 0 0 
1 1 1 0 0 0 
0 9 2 -4 -4 0 
0 0 0 -2 0 0 
0 0 -1 -2 -4 0 
Checking hourglass at (0,0)
1 1 1
  1
1 1 1
hour glass sum = 7
Checking hourglass at (0,1)
1 1 0
  0
1 1 0
hour glass sum = 4
Checking hourglass at (0,2)
1 0 0
  0
1 0 0
hour glass sum = 2
Checking hourglass at (0,3)
0 0 0
  0
0 0 0
hour glass sum = 0
Checking hourglass at (1,0)
0 1 0
  1
0 9 2
hour glass sum = 13
Checking hourglass at (1,1)
1 0 0
  1
9 2 -4
hour glass sum = 9
Checking hourglass at (1,2)
0 0 0
  0
2 -4 -4
hour glass sum = -6
Checking hourglass at (1,3)
0 0 0
  0
-4 -4 0
hour glass sum = -8
Checking hourglass at (2,0)
1 1 1
  9
0 0 0
hour glass sum = 12
Checking hourglass at (2,1)
1 1 0
  2
0 0 -2
hour glass sum = 2
Checking hourglass at (2,2)
1 0 0
  -4
0 -2 0
hour glass sum = -5
Checking hourglass at (2,3)
0 0 0
  -4
-2 0 0
hour glass sum = -6
Checking hourglass at (3,0)
0 9 2
  0
0 0 -1
hour glass sum = 10
Checking hourglass at (3,1)
9 2 -4
  0
0 -1 -2
hour glass sum = 4
Checking hourglass at (3,2)
2 -4 -4
  -2
-1 -2 -4
hour glass sum = -15
Checking hourglass at (3,3)
-4 -4 0
  0
-2 -4 0
hour glass sum = -14
Maximum Hour Glass Sum = 13
